antigo={'Airton Luis Arnoni Neto',
'Alan Richard Teixeira Lucas',
'Alex Lopes Da Silva Pedro',
'Ana Luiza De Lima B. Souza',
'Bruno Cesar De Sousa',
'Caio Ferrareze',
'Cauã Henrique Celegato De Oliveira',
'Cristiane Nerilo',
'Daniel Luis Galrão',
'Daniel Soares Pereira',
'Daniel Wolf Monaro',
'Fernando Aparecido Bailo',
'Gabriel De Lima Alves',
'Gabriel De Souza Pimenta',
'Gabriel Pironato Bonfante',
'Gabriel Trevisan',
'Gabriel Zacarias Soler Dos Santos',
'Giovanna Eliza Lacerda',
'Guilherme Henrique Pateis',
'Guilherme Henrique Ventura',
'Guilherme Rodrigues Ferreira',
'Gustavo Henrique Marçura',
'Henrique Vieira Ribeiro',
'Henry De Jesus Francisco Calle',
'Isabella Dos Santos Cassimiro',
'João Frederico Delgado Benedito',
'João Pedro Furlan',
'João Pedro Gonçalves Abreu Silva',
'Leonardo Bruno Rodrigues',
'Lucas Cavallini Louzada',
'Lucas Eduardo De Celis',
'Lucas Yuami Bartolomei',
'Marcelo Guilherme Pivi Dias',
'Marcos Eduardo Froner',
'Marcos Santana Nunes',
'Mateus Martins Mendonça',
'Matheus De Carvalho Souza',
'Matheus Henrique De Castilho',
'Paulo Victor Gottardi',
'Pedro De Barros',
'Pedro Franco Guidolin',
'Piero Conte',
'Roniel Gardeli Dos Santos',
'Thales Víctor Casséla',
'Victor Gabriel Fernandes Souza',
'Vinícius Emilio Rezende',
'Vítor Hugo De Alencar'}

novo =  {
'Airton Luis Arnoni Neto',
'Alan Richard Teixeira Lucas',
'Alex Lopes Da Silva Pedro',
'Ana Luiza De Lima B. Souza',
'Bruno Cesar De Sousa',
'Caio Ferrareze',
'Cauã Henrique Celegato De Oliveira',
'Cristiane Nerilo',
'Daniel Luis Galrão',
'Daniel Soares Pereira',
'Daniel Wolf Monaro',
'Fernando Aparecido Bailo',
'Gabriel De Lima Alves',
'Gabriel De Souza Pimenta',
'Gabriel Pironato Bonfante',
'Gabriel Trevisan',
'Gabriel Zacarias Soler Dos Santos',
'Giovanna Eliza Lacerda',
'Guilherme Henrique Pateis',
'Guilherme Henrique Ventura',
'Guilherme Rodrigues Ferreira',
'Gustavo Henrique Marçura',
'Henrique Vieira Ribeiro',
'Henry De Jesus Francisco Calle',
'Isabella Dos Santos Cassimiro',
'João Frederico Delgado Benedito',
'João Pedro Furlan',
'João Pedro Gonçalves Abreu Silva',
'Leonardo Bruno Rodrigues',
'Lucas Cavallini Louzada',
'Lucas Eduardo De Celis',
'Lucas Maciel De Oliveira',
'Lucas Yuami Bartolomei',
'Marcelo Guilherme Pivi Dias',
'Marcos Eduardo Froner',
'Marcos Santana Nunes',
'Mateus Martins Mendonça',
'Matheus De Carvalho Souza',
'Matheus Henrique De Castilho',
'Paulo Victor Gottardi',
'Pedro De Barros',
'Pedro Franco Guidolin',
'Piero Conte',
'Roniel Gardeli Dos Santos',
'Thales Víctor Casséla',
'Victor Gabriel Fernandes Souza',
'Vinícius Emilio Rezende',
'Vítor Hugo De Alencar'
}

distinto=novo.difference(antigo)
print(distinto)