porLab = [
    { 'lab': 'Lab1', 'nome': 'DAIVES        ', 'disciplina': 'Algoritmos        ', 'dia':'segunda' },
    { 'lab': 'Lab1', 'nome': 'YURI          ', 'disciplina': 'Imagens           ', 'dia':'quarta' },
    { 'lab': 'Lab1', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia':'quinta' },
    { 'lab': 'Lab1', 'nome': 'MARCOS ANTÔNIO', 'disciplina': 'EngQui            ', 'dia':'sexta' },
    { 'lab': 'Lab1', 'nome': 'DAIVES        ', 'disciplina': 'Algoritmos        ', 'dia':'segunda' },
    { 'lab': 'Lab1', 'nome': 'YURI          ', 'disciplina': 'Logica            ', 'dia':'terça' },
    { 'lab': 'Lab1', 'nome': 'YURI          ', 'disciplina': 'Imagens           ', 'dia':'quarta' },
    { 'lab': 'Lab1', 'nome': 'Jose Ribeiro  ', 'disciplina': 'Contabeis         ', 'dia':'quinta' },
    { 'lab': 'Lab2', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia':'segunda' },
    { 'lab': 'Lab2', 'nome': 'DANIEL        ', 'disciplina': 'Arquitetura       ', 'dia':'terça' },
    { 'lab': 'Lab2', 'nome': 'SAMARA        ', 'disciplina': 'Simulação         ', 'dia':'quarta' },
    { 'lab': 'Lab2', 'nome': 'DANIEL        ', 'disciplina': 'Estrutura         ', 'dia':'quinta' },
    { 'lab': 'Lab2', 'nome': 'LAURA MARIA   ', 'disciplina': 'TCC               ', 'dia':'sexta' },
    { 'lab': 'Lab2', 'nome': 'DANIEL        ', 'disciplina': 'Arquitetura       ', 'dia':'terça' },
    { 'lab': 'Lab2', 'nome': 'DANIEL        ', 'disciplina': 'Estrutura         ', 'dia':'quinta' },
    { 'lab': 'Lab2', 'nome': 'LAURA MARIA   ', 'disciplina': 'TCC               ', 'dia':'sexta' },
    { 'lab': 'Lab3', 'nome': 'DANIEL        ', 'disciplina': 'Arquitetura       ', 'dia':'segunda' },
    { 'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatística       ', 'dia':'terça' },
    { 'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatística       ', 'dia':'quarta' },
    { 'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Algebra           ', 'dia':'quinta' },
    { 'lab': 'Lab3', 'nome': 'Mariana Costa ', 'disciplina': 'EngOv             ', 'dia':'sexta' },
    { 'lab': 'Lab3', 'nome': 'DANIEL        ', 'disciplina': 'Arquitetura       ', 'dia':'segunda' },
    { 'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatistica       ', 'dia':'terça' },
    { 'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatística       ', 'dia':'quarta' },
    { 'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatística       ', 'dia':'quinta' },
    { 'lab': 'Lab3', 'nome': 'Mariana Costa ', 'disciplina': 'EngOv             ', 'dia':'sexta' },
    { 'lab': 'Lab4', 'nome': 'ROSEMARY      ', 'disciplina': 'Projeto Digital   ', 'dia':'segunda' },
    { 'lab': 'Lab4', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia':'terça' },
    { 'lab': 'Lab4', 'nome': 'LUCAS SERAFIM ', 'disciplina': 'Sistemas          ', 'dia':'quarta' },
    { 'lab': 'Lab4', 'nome': 'ROSEMARY      ', 'disciplina': 'Projeto Digital   ', 'dia':'quinta' },
    { 'lab': 'Lab4', 'nome': 'LUCAS SERAFIM ', 'disciplina': 'Sistemas          ', 'dia':'sexta' },
    { 'lab': 'Lab4', 'nome': 'Mariana Costa ', 'disciplina': 'Engov             ', 'dia':'segunda' },
    { 'lab': 'Lab4', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia':'terça' },
    { 'lab': 'Lab4', 'nome': 'LUCAS SERAFIM ', 'disciplina': 'Sistemas          ', 'dia':'quarta' },
    { 'lab': 'Lab4', 'nome': 'ROSEMARY      ', 'disciplina': 'Projeto Digital   ', 'dia':'quinta' },
    { 'lab': 'Lab4', 'nome': 'LUCAS SERAFIM ', 'disciplina': 'Sistemas          ', 'dia':'sexta' },
    { 'lab': 'Lab5', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia':'segunda' },
    { 'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia':'terça' },
    { 'lab': 'Lab5', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia':'quarta' },
    { 'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia':'quinta' },
    { 'lab': 'Lab5', 'nome': 'Laisa Lemes   ', 'disciplina': 'Design            ', 'dia':'sexta' },
    { 'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia':'segunda' },
    { 'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia':'terça' },
    { 'lab': 'Lab5', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia':'quarta' },
    { 'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia':'quinta' },
    { 'lab': 'Lab5', 'nome': 'Laisa Lemes   ', 'disciplina': 'Design            ', 'dia':'sexta' },
    { 'lab': 'Lab6', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia':'segunda' },
    { 'lab': 'Lab6', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia':'terça' },
    { 'lab': 'Lab6', 'nome': 'SANTACLARA    ', 'disciplina': 'Algoritmos        ', 'dia':'quarta' },
    { 'lab': 'Lab6', 'nome': 'Paulo César   ', 'disciplina': 'Estr Dados        ', 'dia':'quinta' },
    { 'lab': 'Lab6', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia':'sexta' },
    { 'lab': 'Lab6', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia':'segunda' },
    { 'lab': 'Lab6', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia':'terça' },
    { 'lab': 'Lab6', 'nome': 'SANTACLARA    ', 'disciplina': 'Algoritmos        ', 'dia':'quarta' },
    { 'lab': 'Lab6', 'nome': 'Paulo César   ', 'disciplina': 'Estr Dados        ', 'dia':'quinta' },
    { 'lab': 'Lab6', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia':'sexta' },
    { 'lab': 'Lab7', 'nome': 'BRUNO HENRIQUE', 'disciplina': 'semMateria        ', 'dia':'segunda' },
    { 'lab': 'Lab7', 'nome': 'Marcos Antônio', 'disciplina': 'EngPr             ', 'dia':'terça' },
    { 'lab': 'Lab7', 'nome': 'FUJITA        ', 'disciplina': 'Estrutura de Dados', 'dia':'quarta' },
    { 'lab': 'Lab7', 'nome': 'SANTACLARA    ', 'disciplina': 'Banco             ', 'dia':'quinta' },
    { 'lab': 'Lab7', 'nome': 'BRUNO HENRIQUE', 'disciplina': 'semMateria        ', 'dia':'segunda' },
    { 'lab': 'Lab7', 'nome': 'Marcos Antônio', 'disciplina': 'EngPr             ', 'dia':'terça' },
    { 'lab': 'Lab7', 'nome': 'FUJITA        ', 'disciplina': 'Estrutura de Dados', 'dia':'quarta' },
    { 'lab': 'Lab7', 'nome': 'SANTACLARA    ', 'disciplina': 'Banco             ', 'dia':'quinta' },
    { 'lab': 'Lab8', 'nome': 'RAUL CESAR    ', 'disciplina': 'Algoritmos        ', 'dia':'segunda' },
    { 'lab': 'Lab8', 'nome': 'FUJITA        ', 'disciplina': 'Interface         ', 'dia':'terça' },
    { 'lab': 'Lab8', 'nome': 'RAUL CESAR    ', 'disciplina': 'Logica            ', 'dia':'quarta' },
    { 'lab': 'Lab8', 'nome': 'FUJITA        ', 'disciplina': 'Arquitetura       ', 'dia':'quinta' },
    { 'lab': 'Lab8', 'nome': 'SANTACLARA    ', 'disciplina': 'Banco             ', 'dia':'sexta' },
    { 'lab': 'Lab8', 'nome': 'RAUL CESAR    ', 'disciplina': 'Algoritmos        ', 'dia':'segunda' },
    { 'lab': 'Lab8', 'nome': 'RAUL CESAR    ', 'disciplina': 'Logica            ', 'dia':'terça' },
    { 'lab': 'Lab8', 'nome': 'TAGLIETTA     ', 'disciplina': 'SO                ', 'dia':'quarta' },
    { 'lab': 'Lab8', 'nome': 'TAGLIETTA     ', 'disciplina': 'SO                ', 'dia':'quinta' },
    { 'lab': 'Lab8', 'nome': 'SANTACLARA    ', 'disciplina': 'Banco             ', 'dia':'sexta' }
]

porDia = [
    {'lab': 'Lab1', 'nome': 'DAIVES        ', 'disciplina': 'Algoritmos        ', 'dia': 'segunda'},
    {'lab': 'Lab1', 'nome': 'DAIVES        ', 'disciplina': 'Algoritmos        ', 'dia': 'segunda'},
    {'lab': 'Lab2', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia': 'segunda'},
    {'lab': 'Lab3', 'nome': 'DANIEL        ', 'disciplina': 'Arquitetura       ', 'dia': 'segunda'},
    {'lab': 'Lab3', 'nome': 'DANIEL        ', 'disciplina': 'Arquitetura       ', 'dia': 'segunda'},
    {'lab': 'Lab4', 'nome': 'ROSEMARY      ', 'disciplina': 'Projeto Digital   ', 'dia': 'segunda'},
    {'lab': 'Lab4', 'nome': 'Mariana Costa ', 'disciplina': 'Engov             ', 'dia': 'segunda'},
    {'lab': 'Lab5', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia': 'segunda'},
    {'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia': 'segunda'},
    {'lab': 'Lab6', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia': 'segunda'},
    {'lab': 'Lab6', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia': 'segunda'},
    {'lab': 'Lab7', 'nome': 'BRUNO HENRIQUE', 'disciplina': 'semMateria        ', 'dia': 'segunda'},
    {'lab': 'Lab7', 'nome': 'BRUNO HENRIQUE', 'disciplina': 'semMateria        ', 'dia': 'segunda'},
    {'lab': 'Lab8', 'nome': 'RAUL CESAR    ', 'disciplina': 'Algoritmos        ', 'dia': 'segunda'},
    {'lab': 'Lab8', 'nome': 'RAUL CESAR    ', 'disciplina': 'Algoritmos        ', 'dia': 'segunda'},
    {'lab': 'Lab1', 'nome': 'YURI          ', 'disciplina': 'Logica            ', 'dia': 'terça'},
    {'lab': 'Lab2', 'nome': 'DANIEL        ', 'disciplina': 'Arquitetura       ', 'dia': 'terça'},
    {'lab': 'Lab2', 'nome': 'DANIEL        ', 'disciplina': 'Arquitetura       ', 'dia': 'terça'},
    {'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatística       ', 'dia': 'terça'},
    {'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatistica       ', 'dia': 'terça'},
    {'lab': 'Lab4', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia': 'terça'},
    {'lab': 'Lab4', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia': 'terça'},
    {'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia': 'terça'},
    {'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia': 'terça'},
    {'lab': 'Lab6', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia': 'terça'},
    {'lab': 'Lab6', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia': 'terça'},
    {'lab': 'Lab7', 'nome': 'Marcos Antônio', 'disciplina': 'EngPr             ', 'dia': 'terça'},
    {'lab': 'Lab7', 'nome': 'Marcos Antônio', 'disciplina': 'EngPr             ', 'dia': 'terça'},
    {'lab': 'Lab8', 'nome': 'FUJITA        ', 'disciplina': 'Interface         ', 'dia': 'terça'},
    {'lab': 'Lab8', 'nome': 'RAUL CESAR    ', 'disciplina': 'Logica            ', 'dia': 'terça'},
    {'lab': 'Lab1', 'nome': 'YURI          ', 'disciplina': 'Imagens           ', 'dia': 'quarta'},
    {'lab': 'Lab1', 'nome': 'YURI          ', 'disciplina': 'Imagens           ', 'dia': 'quarta'},
    {'lab': 'Lab2', 'nome': 'SAMARA        ', 'disciplina': 'Simulação         ', 'dia': 'quarta'},
    {'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatística       ', 'dia': 'quarta'},
    {'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatística       ', 'dia': 'quarta'},
    {'lab': 'Lab4', 'nome': 'LUCAS SERAFIM ', 'disciplina': 'Sistemas          ', 'dia': 'quarta'},
    {'lab': 'Lab4', 'nome': 'LUCAS SERAFIM ', 'disciplina': 'Sistemas          ', 'dia': 'quarta'},
    {'lab': 'Lab5', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia': 'quarta'},
    {'lab': 'Lab5', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia': 'quarta'},
    {'lab': 'Lab6', 'nome': 'SANTACLARA    ', 'disciplina': 'Algoritmos        ', 'dia': 'quarta'},
    {'lab': 'Lab6', 'nome': 'SANTACLARA    ', 'disciplina': 'Algoritmos        ', 'dia': 'quarta'},
    {'lab': 'Lab7', 'nome': 'FUJITA        ', 'disciplina': 'Estrutura de Dados', 'dia': 'quarta'},
    {'lab': 'Lab7', 'nome': 'FUJITA        ', 'disciplina': 'Estrutura de Dados', 'dia': 'quarta'},
    {'lab': 'Lab8', 'nome': 'RAUL CESAR    ', 'disciplina': 'Logica            ', 'dia': 'quarta'},
    {'lab': 'Lab8', 'nome': 'TAGLIETTA     ', 'disciplina': 'SO                ', 'dia': 'quarta'},
    {'lab': 'Lab1', 'nome': 'VALMIR        ', 'disciplina': 'Design            ', 'dia': 'quinta'},
    {'lab': 'Lab1', 'nome': 'Jose Ribeiro  ', 'disciplina': 'Contabeis         ', 'dia': 'quinta'},
    {'lab': 'Lab2', 'nome': 'DANIEL        ', 'disciplina': 'Estrutura         ', 'dia': 'quinta'},
    {'lab': 'Lab2', 'nome': 'DANIEL        ', 'disciplina': 'Estrutura         ', 'dia': 'quinta'},
    {'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Algebra           ', 'dia': 'quinta'},
    {'lab': 'Lab3', 'nome': 'FABIO         ', 'disciplina': 'Estatística       ', 'dia': 'quinta'},
    {'lab': 'Lab4', 'nome': 'ROSEMARY      ', 'disciplina': 'Projeto Digital   ', 'dia': 'quinta'},
    {'lab': 'Lab4', 'nome': 'ROSEMARY      ', 'disciplina': 'Projeto Digital   ', 'dia': 'quinta'},
    {'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia': 'quinta'},
    {'lab': 'Lab5', 'nome': 'SINCLAIR      ', 'disciplina': 'Design            ', 'dia': 'quinta'},
    {'lab': 'Lab6', 'nome': 'Paulo César   ', 'disciplina': 'Estr Dados        ', 'dia': 'quinta'},
    {'lab': 'Lab6', 'nome': 'Paulo César   ', 'disciplina': 'Estr Dados        ', 'dia': 'quinta'},
    {'lab': 'Lab7', 'nome': 'SANTACLARA    ', 'disciplina': 'Banco             ', 'dia': 'quinta'},
    {'lab': 'Lab7', 'nome': 'SANTACLARA    ', 'disciplina': 'Banco             ', 'dia': 'quinta'},
    {'lab': 'Lab8', 'nome': 'FUJITA        ', 'disciplina': 'Arquitetura       ', 'dia': 'quinta'},
    {'lab': 'Lab8', 'nome': 'TAGLIETTA     ', 'disciplina': 'SO                ', 'dia': 'quinta'},
    {'lab': 'Lab1', 'nome': 'MARCOS ANTÔNIO', 'disciplina': 'EngQui            ', 'dia': 'sexta'},
    {'lab': 'Lab2', 'nome': 'LAURA MARIA   ', 'disciplina': 'TCC               ', 'dia': 'sexta'},
    {'lab': 'Lab2', 'nome': 'LAURA MARIA   ', 'disciplina': 'TCC               ', 'dia': 'sexta'},
    {'lab': 'Lab3', 'nome': 'Mariana Costa ', 'disciplina': 'EngOv             ', 'dia': 'sexta'},
    {'lab': 'Lab3', 'nome': 'Mariana Costa ', 'disciplina': 'EngOv             ', 'dia': 'sexta'},
    {'lab': 'Lab4', 'nome': 'LUCAS SERAFIM ', 'disciplina': 'Sistemas          ', 'dia': 'sexta'},
    {'lab': 'Lab4', 'nome': 'LUCAS SERAFIM ', 'disciplina': 'Sistemas          ', 'dia': 'sexta'},
    {'lab': 'Lab5', 'nome': 'Laisa Lemes   ', 'disciplina': 'Design            ', 'dia': 'sexta'},
    {'lab': 'Lab5', 'nome': 'Laisa Lemes   ', 'disciplina': 'Design            ', 'dia': 'sexta'},
    {'lab': 'Lab6', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia': 'sexta'},
    {'lab': 'Lab6', 'nome': 'SEBASTIÃO     ', 'disciplina': 'Sistemas          ', 'dia': 'sexta'},
    {'lab': 'Lab8', 'nome': 'SANTACLARA    ', 'disciplina': 'Banco             ', 'dia': 'sexta'},
    {'lab': 'Lab8', 'nome': 'SANTACLARA    ', 'disciplina': 'Banco             ', 'dia': 'sexta'}
]

for i in range(len(porDia)):
    if 'FUJITA' in porDia[i]['nome']:
        print(f"{porDia[i]['lab']:<6} {porDia[i]['disciplina']:<30} {porDia[i]['dia']:<10}")

def organizaPorDia(dia):
    for i in range(len(porDia)):
        if porDia[i]['dia'] == dia:
            print(porDia[i])

# organizaPorDia('segunda')
# organizaPorDia('terça')
# organizaPorDia('quarta')
# organizaPorDia('quinta')
# organizaPorDia('sexta')
