print("hello world", type("hello world"))
print(20, type(20))
print(3.14, type(3.14))
print(1j, type(1j))
print('["um","dois","tres"]', type(["um","dois","tres"]))
print('("um","dois","tres")', type(("um","dois","tres")))
print('range(10)',type(range(10)))
print('{"language":"Python", "job":"developer"}',type({"language":"Python", "job":"developer"}))
print('{"um","dois","tres"}',type({"um","dois","tres"}))
print('fronzenset({"um","dois","tres"})',type(frozenset({"um","dois","tres"})))
print('True',type(True))
print('b"Hello"',type(b"Hello"))
print('bytearray(5)',type(bytearray(5)))
print('memoryview(bytes(5))',type(memoryview(bytes(5))))
print('None',type(None))
